spring:
  application:
    name: activityservice
  config:
    import: optional:configserver:http://localhost:8888

  #rabbitmq:
   # queue:
    #  name: activity.queue
    #exchange:
     # name: fitness.exchange
    #routing:
     # key: activity.tracking

