spring:
  application:
    name: activityservice
  data:
    mongodb:
      host: localhost       # <--- ΝΕΑ ΡΥΘΜΙΣΗ
      port: 27017           # <--- ΝΕΑ ΡΥΘΜΙΣΗ
      database: fitnessactivity # <--- ΚΡΑΤΑΜΕ ΤΟ ΣΩΣΤΟ ΟΝΟΜΑ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    exchange:
      name: fitness.exchange
    queue:
      name: activity.queue
    routing:
      key: activity.tracking


server:
  port: 8082

logging:
  level:
    org.springframework.data.mongodb.core: DEBUG
    org.mongodb.driver: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8799/eureka/
  instance:
    # 1. Αναγκάζει το service να καταχωρηθεί με IP αντί για hostname
    prefer-ip-address: true
    # 2. Χρησιμοποιεί ρητά το localhost (127.0.0.1) ως IP
    ip-address: 127.0.0.1

